name: PHP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Kiểm tra code từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Thiết lập PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Chọn phiên bản PHP
        tools: composer # Cài đặt Composer

    # 3. Cài đặt các phụ thuộc
    - name: Install dependencies
      run: composer install

    # 4. Chạy kiểm thử với PHPUnit
    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml

    # 5. Build ứng dụng
    - name: Build application
      run: |
        echo "Building PHP application..."
        mkdir build
        rsync -av --exclude='build' ./ build/
        tar -czvf build.tar.gz build/
        echo "Application built successfully."
